kind: Service
apiVersion: v1
metadata:
  name: ${CICD_GIT_REPO_NAME}-service
  namespace: default
spec:
  selector:
    app: ${CICD_GIT_REPO_NAME}
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${CICD_GIT_REPO_NAME}
  namespace: default
  labels:
    app: ${CICD_GIT_REPO_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${CICD_GIT_REPO_NAME}
  template:
    metadata:
      labels:
        app: ${CICD_GIT_REPO_NAME}
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: ${CICD_GIT_REPO_NAME}
        image: ${CICD_IMAGE}:${CICD_GIT_BRANCH}
        ports:
        - containerPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ${CICD_GIT_REPO_NAME}
  namespace: default
spec:
  rules:
  - host: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}.edu-edomex.gob.mx
    http:
      paths:
      - backend:
          serviceName: ${CICD_GIT_REPO_NAME}-service
          servicePort: 8080
status:
  loadBalancer:
    ingress:
    - ip: 10.33.220.135
    - ip: 10.33.220.136
    - ip: 10.33.220.137
